# Generated by Django 5.1.5 on 2025-03-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uplodfiles',
            old_name='upload_time',
            new_name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='uplodfiles',
            name='file_url',
            field=models.TextField(),
        ),
    ]
